# Generated by Django 2.2 on 2019-11-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
